title: "Adriaan van Rossum's projects"
name: "Adriaan van Rossum's projects"
description: 'Adriaan does a lot of things, find out what!'
author:
  name: 'Adriaan van Rossum'
permalink: '/:title'
timezone: 'Europe/Amsterdam'
locale: 'en'
logo: '/images/adriaan-van-rossum-silhouette.png'
sass:
  sass_dir: assets/sass

defaults:
  -
    scope:
      path: ''
    values:
      layout: 'base'
      type: 'pages'

gems:
  - jemoji
